enable = ["ALL"]

[MD013]
line-length = 0 # Disable all line length checks
reflow = true
reflow-mode = "sentence-per-line"

[code-block-tools]
enabled = true
on-missing-language-definition = "fail"
on-missing-tool-binary = "fail"

[code-block-tools.languages]
shell = {lint = ["shuck"], format = ["shfmt"]}
