name: Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    name: test with ${{ matrix.py }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.14"
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          python-version: ${{ matrix.py }}
      - name: Sync deps
        run: uv sync --extra dev --locked
      - name: Run test suite
        run: uv run pytest --import-mode importlib

  e2e-tests:
    runs-on: ubuntu-latest
    name: run ${{ matrix.tool }} try-repo on all files
    strategy:
      fail-fast: false
      matrix:
        tool:
          - pre-commit
          - prek
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          python-version: "3.14"
      - name: Run ${{ matrix.tool }} try repo
        run: SKIP=check-jira-reference-in-todo,go-revive,go-fmt,go-imports,check-number-of-lines-count,check-ownership uvx ${{ matrix.tool }} try-repo "$PWD" --all-files --verbose
