name: Publish package to PyPI

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ inputs.package_name }}
    permissions:
      id-token: write # Required for trusted (OIDC) publishing
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Validate tag version against pyproject.toml
        run: ./scripts/check_release.sh "${{ github.ref_name }}"
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          python-version: "3.12"
      - name: Build ${{ inputs.package_name }} package
        run: uv build --package ${{ inputs.package_name }}
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # release/v1
        with:
          packages-dir: dist/
