name: Publish whoowns to PyPI

on:
  push:
    tags:
      - 'whoowns-*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/whoowns
    permissions:
      id-token: write # Required for trusted (OIDC) publishing
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7
        with:
          python-version: "3.12"
      - name: Build whoowns package
        run: uv build --package whoowns
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
